### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/james-stephens_the-crock-of-gold#2]
https://github.com/standardebooks/james-stephens_the-crock-of-gold/blob/ddf0083ac54c22a4924bcc1a16c4013f617296dd/src/epub/text/chapter-17.xhtml#L58

"I’ve got a twist, my eye trying to watch them."

should be

"I’ve got a twist in my eye trying to watch them."

Also:

"...neighborliness, terrible, terrible creatures."

should be

"...neighborliness; terrible, terrible creatures." (semicolon)

see: https://www.google.com/books/edition/THE_CRACK_OF_GOLD/gf1igtdlvukC?hl=en&gbpv=1&pg=PA271&printsec=frontcover

**Comment by acabal** [comment]
Thanks, these should be fixed now!
